### ISSUE TITLE
Official integration

### ISSUE THREAD

**Issue by gagebenne** [joshjcarrier/homeassistant-litter-robot#23]
I enjoy using your custom component, and I'm just curious why you haven't pursued making it an official integration?

I would love to help if that is something you're after.

**Comment by joshjcarrier** [comment]
Yeah this sounds like a good idea now, I'm a little happier with the code structure and I found [this guide](https://developers.home-assistant.io/docs/integration_quality_scale_index) on acceptable official integration quality.

**Comment by gagebenne** [comment]
Yeah, I'm sure the first step would probably be breaking out the Litter-Robot API into a package. You have it pretty well documented, so shouldn't be too bad.

Again, would love to help out, but don't want to step on the great stuff you've got. Just let me know ;)!

**Comment by NicoSomerwil** [comment]
Hi there,

great to see your integration since HA 0.113. As my wife is diabetic for many years and is using the Dexcom G6 sensor I was very glad that there is support for it in HA. Unfortunately I can't get it working yet. When my wife add me as a follower in the iOS app I get just an e-mail which links me directly to the Dexcom Follow app. So I don't get any credentials to use within the integration. Searched, but didn't find a way to create a username and password within the mobile app. 
Then I logged in at https://uam2.dexcom.com/index.html#/profile (server for people like us (from the Netherlands) outside the US). I noticed there that I could make another profile, which I did. But no luck using this credentials to get the expected data from my wife's G6 sensor. The two expected entities are shown but no data. Also there is nothing (yet) in the logging. As I'm still a beginner, I guess I'm doing something wrong so maybe you are willing to point me in the right direction to get it working or help me a step further. By the way, sorry for my English, but hopefully you will get the point. Thanks for your integration, I'm sure when more and more people will discover it, it will be of great help for diabetics. Best Regards, Nico

**Comment by joshjcarrier** [comment]
@gagebenne I've been trying to get #30 Translations to work and it seems to be hit-or-miss (mostly miss) for whether translations load, do you have any experience?

**Comment by allenporter** [comment]
Hi, are you interested in making this an official integration? I recently contributed an integration and was curious if you needed any help.

**Comment by stimpy2318** [comment]
Just thought I would throw my $0.02 in as well, I would love to see this as an official integration in home assistant. I just upgraded my Litter Robot with the Connect Kit as I needed to also replace the DFI sensors after an issue with them failing and since I was in there decided to drop the extra money to go ahead and make my Spaceship (that is what we call ours) smart. I haven't played with this addon yet but I might try the manual installation tomorrow to try it out. Would be great to get it into the official repos though to make upgrades and the like easier down the line. I do have some mild to moderate python skills but haven't done much development for HA yet (other than a custom script to handle Alexa volume changes) if you need any help feel free to let me know.

**Comment by cchiapusio** [comment]
someone has gotten a litterrobot integration added into HACS:  https://github.com/natekspencer
