### ISSUE TITLE
multiple robots

### ISSUE THREAD

**Issue by thayneq** [joshjcarrier/homeassistant-litter-robot#6]
Hi,

I just wanted to drop you a line and tell you that this project is amazing! Thanks so much for supporting this niche device!

I love my litter robot so much I bought a second one. Looking forward to multiple robot support!

Also, have you considered adding this as an official component to the hass.io repo?

**Comment by joshjcarrier** [comment]
Cool, was thinking about getting another robot since I have 3 cats now but I don't have any space!

I'd like to see this as part of hass.io (as discussed in https://github.com/joshjcarrier/homeassistant-litter-robot/pull/3) but given there are 0 tests I don't think it would meet the quality bar quite yet!

**Comment by thayneq** [comment]
Just learned about HACS. I'll definitely check that out if it's supported.

I have 5 cats, and before the litter Robot we had 3 boxes. Now I have two litter robots and it's perfect.

Looking forward to any future updates!

**Comment by joshjcarrier** [comment]
@thayneq can you try this branch and see if it works for you? https://github.com/joshjcarrier/homeassistant-litter-robot/archive/feat/multiple_robots.zip

**Comment by thayneq** [comment]
wow! Works great! I see both my robots and I'm able to independently cycle each one. Thanks!
